on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - "*"

name: Build
jobs:
  baseline:
    runs-on:
      - ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5

      - name: Test
        run: go test ./...

  # namespace:
  #   runs-on:
  #     - namespace-profile-default
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Install Go
  #       uses: actions/setup-go@v5
  #       with:
  #         cache: false

  #     - name: Setup runner cache
  #       uses: namespacelabs/nscloud-cache-action@v1
  #       with:
  #         cache: go

  #     - name: Test
  #       run: go test ./...
