on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - "*"

name: Build
jobs:
  baseline:
    runs-on:
      - ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x

      - name: Test
        run: go test ./...

  namespace:
    strategy:
      matrix:
        foo: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
        bar: [0, 1]
    runs-on:
      - namespace-profile-cache-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          cache: false
          go-version: 1.23.x

      - name: Setup runner cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          cache: go

      - name: Test
        run: go test ./...
