on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
name: Check Formatting
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.21.x]
    runs-on:
      - nscloud-ubuntu-22.04-amd64-2x8-with-cache
      - nscloud-cache-size-10gb
      - nscloud-cache-tag-foundation-golang
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: false
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup cross-invocation caching
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          cache: go
      - name: Build ns
        env:
          CGO_ENABLED: 0
        run: go build -v -o ns ./cmd/ns
      - name: Check Formatting
        run: ./ns fmt --all --check
      - name: Breakpoint on failure
        if: failure() && github.ref_name == 'main'
        uses: namespacelabs/breakpoint-action@v0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          duration: 15m
          authorized-users: edganiukov,hugosantos,n-g,htr,nichtverstehen,gmichelo
          slack-announce-channel: "#ci"
