on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.21.x]
    runs-on:
      - nscloud-ubuntu-22.04-amd64-8x16-with-cache
      - nscloud-cache-size-10gb
      - nscloud-cache-tag-foundation-golang
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: false

      - name: Setup runner cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          cache: go

      - name: Test
        run: go test ./...
      - name: Check Go Formatting
        run: go fmt ./... && git diff --exit-code
      - name: Check Go Mod Tidyness
        run: go mod tidy && git diff --exit-code

      - name: Breakpoint on failure
        if: failure() && github.ref_name == 'main'
        uses: namespacelabs/breakpoint-action@v0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          duration: 15m
          authorized-users: edganiukov,hugosantos,n-g,htr,nichtverstehen,gmichelo
          slack-announce-channel: "#ci"
